/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "primary-fixed": "#dbe1ff",
              "surface-container-low": "#eff4ff",
              "tertiary-fixed-dim": "#ffb95f",
              "on-tertiary-container": "#ffeedd",
              "secondary-container": "#6cf8bb",
              "surface-container": "#e5eeff",
              "primary-fixed-dim": "#b4c5ff",
              "outline-variant": "#c3c6d7",
              "on-tertiary": "#ffffff",
              "on-secondary-fixed-variant": "#005236",
              "surface-container-highest": "#d3e4fe",
              "on-background": "#0b1c30",
              "surface-tint": "#0053db",
              "tertiary-fixed": "#ffddb8",
              "on-surface": "#0b1c30",
              "surface-bright": "#f8f9ff",
              "inverse-on-surface": "#eaf1ff",
              "on-secondary-container": "#00714d",
              "background": "#f8f9ff",
              "on-surface-variant": "#434655",
              "surface": "#f8f9ff",
              "secondary-fixed": "#6ffbbe",
              "secondary-fixed-dim": "#4edea3",
              "on-secondary-fixed": "#002113",
              "inverse-primary": "#b4c5ff",
              "on-primary-container": "#eeefff",
              "tertiary": "#784b00",
              "tertiary-container": "#996100",
              "surface-container-lowest": "#ffffff",
              "surface-dim": "#cbdbf5",
              "outline": "#737686",
              "error-container": "#ffdad6",
              "primary-container": "#2563eb",
              "on-secondary": "#ffffff",
              "on-primary-fixed": "#00174b",
              "secondary": "#006c49",
              "inverse-surface": "#213145",
              "error": "#ba1a1a",
              "on-error": "#ffffff",
              "primary": "#004ac6",
              "on-primary-fixed-variant": "#003ea8",
              "surface-variant": "#d3e4fe",
              "on-tertiary-fixed": "#2a1700",
              "on-primary": "#ffffff",
              "on-error-container": "#93000a",
              "on-tertiary-fixed-variant": "#653e00",
              "surface-container-high": "#dce9ff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "base": "4px",
              "lg": "24px",
              "stack-gap": "12px",
              "edge-margin": "16px",
              "md": "16px",
              "xs": "4px",
              "sm": "8px",
              "xl": "32px"
      }
    },
  },
  plugins: [],
}
