/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{svelte,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#edf0ff",
        "outline-variant": "#c3c6d6",
        "primary-container": "#0052cc",
        "secondary": "#5e4db9",
        "surface-variant": "#d8e2ff",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#b2c5ff",
        "primary": "#003d9b",
        "primary-fixed": "#dae2ff",
        "on-secondary-container": "#341d8d",
        "surface-container-low": "#f1f3ff",
        "tertiary": "#004b59",
        "tertiary-fixed-dim": "#48d7f9",
        "tertiary-container": "#006477",
        "surface-dim": "#ccdaff",
        "surface-tint": "#0c56d0",
        "secondary-fixed": "#e5deff",
        "surface-container-high": "#e1e8ff",
        "secondary-container": "#9f8eff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#0040a2",
        "on-secondary-fixed-variant": "#4633a0",
        "on-surface": "#051a3e",
        "surface-container-highest": "#d8e2ff",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#1a0063",
        "background": "#faf9ff",
        "on-tertiary-container": "#76e2ff",
        "on-tertiary-fixed-variant": "#004e5d",
        "on-primary-container": "#c4d2ff",
        "inverse-surface": "#1d3054",
        "on-background": "#051a3e",
        "outline": "#737685",
        "surface": "#faf9ff",
        "inverse-primary": "#b2c5ff",
        "on-surface-variant": "#434654",
        "surface-container": "#e9edff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001848",
        "surface-bright": "#faf9ff",
        "secondary-fixed-dim": "#c9bfff",
        "on-tertiary-fixed": "#001f27",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#afecff",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-padding": "16px",
        "base": "4px",
        "md": "16px",
        "xs": "4px",
        "lg": "24px",
        "sm": "8px",
        "stack-gap": "20px",
        "xl": "32px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "label-sm": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-lg": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["22px", {"lineHeight": "28px", "fontWeight": "700"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}],
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
