-- Target Lists containing leads
CREATE TABLE target_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Campaigns targeting specific lists
CREATE TABLE campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    spintax_template TEXT,
    use_llm_personalization BOOLEAN DEFAULT FALSE NOT NULL,
    target_list_id BIGINT,
    status VARCHAR(50) DEFAULT 'DRAFT' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_campaigns_target_list FOREIGN KEY (target_list_id) REFERENCES target_lists(id) ON DELETE SET NULL
);

-- Leads belonging to target lists
CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_list_id BIGINT,
    username VARCHAR(255),
    phone_number VARCHAR(100),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    metadata TEXT, -- JSON or plain text metadata for personalization
    status VARCHAR(50) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_leads_target_list FOREIGN KEY (target_list_id) REFERENCES target_lists(id) ON DELETE CASCADE
);
