-- CRM Query Optimization Schema

CREATE TABLE IF NOT EXISTS telegram_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(255) NOT NULL,
    username VARCHAR(255),
    session_status VARCHAR(50) DEFAULT 'ACTIVE' NOT NULL,
    status VARCHAR(50) DEFAULT 'ACTIVE' NOT NULL,
    proxy VARCHAR(255),
    current_trust_score DOUBLE PRECISION DEFAULT 0.0,
    is_warmed_up BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_list_id BIGINT,
    username VARCHAR(255),
    phone_number VARCHAR(100),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    metadata TEXT,
    status VARCHAR(50) DEFAULT 'PENDING' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_account_id BIGINT NOT NULL,
    lead_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    last_message_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_chats_account FOREIGN KEY (telegram_account_id) REFERENCES telegram_accounts(id),
    CONSTRAINT fk_chats_lead FOREIGN KEY (lead_id) REFERENCES leads(id)
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    sender_type VARCHAR(50) NOT NULL,
    text TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_chat_messages_chat FOREIGN KEY (chat_id) REFERENCES chats(id)
);

-- Index for fast unified inbox queries by status and account, ordered by last_message_at DESC
CREATE INDEX idx_chats_account_status_last_msg ON chats(telegram_account_id, status, last_message_at DESC);

-- View for unified inbox presentation
CREATE VIEW unified_inbox_view AS
SELECT
    c.id AS chat_id,
    c.status AS chat_status,
    c.last_message_at AS last_message_at,
    a.id AS telegram_account_id,
    a.phone_number AS account_phone_number,
    a.session_status AS account_status,
    l.id AS lead_id,
    l.username AS lead_username,
    l.phone_number AS lead_phone_number,
    l.status AS lead_status
FROM chats c
JOIN telegram_accounts a ON c.telegram_account_id = a.id
JOIN leads l ON c.lead_id = l.id;
