-- Flyway migration V20260726003211236 to define schema for telegram dispatch logs
-- Enforce daily messaging rate limits

CREATE TABLE telegram_dispatch_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    recipient_username VARCHAR(255),
    recipient_phone VARCHAR(50),
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_dispatch_logs_account FOREIGN KEY (account_id) REFERENCES tg_accounts(id) ON DELETE CASCADE
);

CREATE INDEX idx_telegram_dispatch_logs_account_sent_at ON telegram_dispatch_logs(account_id, sent_at);
