-- Flyway migration to define schema for telegram accounts, trust scores, and warm-up/action logs
-- Version: V20260726003721423

CREATE TABLE IF NOT EXISTS telegram_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number VARCHAR(255) NOT NULL,
    username VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    proxy VARCHAR(255),
    current_trust_score DOUBLE PRECISION DEFAULT 0.0,
    is_warmed_up BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE telegram_account_trust_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trust_scores_account FOREIGN KEY (account_id) REFERENCES telegram_accounts(id) ON DELETE CASCADE
);

CREATE TABLE telegram_account_warm_up_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    action VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    details VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_warm_up_logs_account FOREIGN KEY (account_id) REFERENCES telegram_accounts(id) ON DELETE CASCADE
);

-- Optimize filtering performance (Kano: Performance)
CREATE INDEX idx_telegram_accounts_filtering ON telegram_accounts(is_warmed_up, current_trust_score, status);
CREATE INDEX idx_trust_scores_account_id ON telegram_account_trust_scores(account_id);
CREATE INDEX idx_warm_up_logs_account_id ON telegram_account_warm_up_logs(account_id);
